services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tasktrackpro_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TaskTrack123!
    ports:
      - "1433:1433"
    restart: always
